CREATE TABLE IF NOT EXISTS {table_name} (
    OutID uuid primary key,
    Birth smallint,
    SexTypeName varchar(128),
    Regname varchar(256),
    AreaName varchar(512),
    TerName  varchar(256),
    RegTypeName varchar(1024),
    TerTypeName varchar(128),
    ClassProfileName varchar(256),
    ClassLangName varchar(256),
    EOName text,
    EOTypeName varchar(512),
    EORegName text,
    EOAreaName varchar(512),
    EOTerName varchar(256),
    EOParent text,
    --UKR TEST
    UkrTest VARCHAR (512),
    UkrTestStatus VARCHAR (256),
    UkrBall100 smallint,
    UkrBall12 smallint,
    UkrBall smallint,
    UkrAdaptScale smallint default 0,
    UkrPTName text,
    UkrPTRegName text,
    UkrPTAreaName  varchar(512),
    UkrPTTerName varchar(256),
    --HIST TEST
    histTest VARCHAR (512),
    HistLang VARCHAR (512),
    histTestStatus VARCHAR (256),
    histBall100 smallint,
    histBall12 smallint,
    histBall smallint,
    histPTName text,
    histPTRegName text,
    histPTAreaName  varchar(512),
    histPTTerName varchar(256),
    --MATH TEST
    mathTest VARCHAR (512),
    mathLang VARCHAR (512),
    mathTestStatus VARCHAR (256),
    mathBall100 smallint,
    mathBall12 smallint,
    mathBall smallint,
    mathPTName text,
    mathPTRegName text,
    mathPTAreaName  varchar(512),
    mathPTTerName varchar(256),
    --PHYS TEST
    physTest VARCHAR (512),
    physLang VARCHAR (512),
    physTestStatus VARCHAR (256),
    physBall100 smallint,
    physBall12 smallint,
    physBall smallint,
    physPTName text,
    physPTRegName text,
    physPTAreaName  varchar(512),
    physPTTerName varchar(256),
    --CHEM TEST
    chemTest VARCHAR (512),
    chemLang VARCHAR (512),
    chemTestStatus VARCHAR (256),
    chemBall100 smallint,
    chemBall12 smallint,
    chemBall smallint,
    chemPTName text,
    chemPTRegName text,
    chemPTAreaName  varchar(512),
    chemPTTerName varchar(256),
    --BIO TEST
    bioTest VARCHAR (512),
    bioLang VARCHAR (512),
    bioTestStatus VARCHAR (256),
    bioBall100 smallint,
    bioBall12 smallint,
    bioBall smallint,
    bioPTName text,
    bioPTRegName text,
    bioPTAreaName  varchar(512),
    bioPTTerName varchar(256),
    --GEO TEST
    geoTest VARCHAR (512),
    geoLang VARCHAR (512),
    geoTestStatus VARCHAR (256),
    geoBall100 smallint,
    geoBall12 smallint,
    geoBall smallint,
    geoPTName text,
    geoPTRegName text,
    geoPTAreaName  varchar(512),
    geoPTTerName varchar(256),
    --ENG TEST
    engTest VARCHAR (512),
    engTestStatus VARCHAR (256),
    engBall100 smallint,
    engBall12 smallint,
    engDPALevel VARCHAR (512),
    engBall smallint,
    engPTName text,
    engPTRegName text,
    engPTAreaName  varchar(512),
    engPTTerName varchar(256),
    --FRA TEST
    fraTest VARCHAR (512),
    fraTestStatus VARCHAR (256),
    fraBall100 smallint,
    fraBall12 smallint,
    fraDPALevel VARCHAR (512),
    fraBall smallint,
    fraPTName text,
    fraPTRegName text,
    fraPTAreaName  varchar(512),
    fraPTTerName varchar(256),
    --DEU TEST
    deuTest VARCHAR (512),
    deuTestStatus VARCHAR (256),
    deuBall100 smallint,
    deuBall12 smallint,
    deuDPALevel VARCHAR (512),
    deuBall smallint,
    deuPTName text,
    deuPTRegName text,
    deuPTAreaName  varchar(512),
    deuPTTerName varchar(256),
    --SPA TEST
    spaTest VARCHAR (512),
    spaTestStatus VARCHAR (256),
    spaBall100 smallint,
    spaBall12 smallint,
    spaDPALevel VARCHAR(512),
    spaBall smallint,
    spaPTName text,
    spaPTRegName text,
    spaPTAreaName  varchar(512),
    spaPTTerName varchar(256),
    --TEST YEAR
    TestYear smallint
);
