wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.6
    framework: torch
    huggingface_version: 3.1.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.1
adam_epsilon:
  desc: null
  value: 1.0e-08
best_model_dir:
  desc: null
  value: outputs/best_model
cache_dir:
  desc: null
  value: cache_dir/
config:
  desc: null
  value: {}
custom_layer_parameters:
  desc: null
  value: []
custom_parameter_groups:
  desc: null
  value: []
dataloader_num_workers:
  desc: null
  value: 6
do_lower_case:
  desc: null
  value: false
dynamic_quantize:
  desc: null
  value: false
early_stopping_consider_epochs:
  desc: null
  value: false
early_stopping_delta:
  desc: null
  value: 0
early_stopping_metric:
  desc: null
  value: eval_loss
early_stopping_metric_minimize:
  desc: null
  value: true
early_stopping_patience:
  desc: null
  value: 3
encoding:
  desc: null
  value: null
eval_batch_size:
  desc: null
  value: 64
evaluate_during_training:
  desc: null
  value: true
evaluate_during_training_silent:
  desc: null
  value: true
evaluate_during_training_steps:
  desc: null
  value: 100
evaluate_during_training_verbose:
  desc: null
  value: false
fp16:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 1
labels_list:
  desc: null
  value:
  - 0
  - 1
labels_map:
  desc: null
  value: {}
lazy_delimiter:
  desc: null
  value: "\t"
lazy_labels_column:
  desc: null
  value: 1
lazy_loading:
  desc: null
  value: false
lazy_loading_start_line:
  desc: null
  value: 1
lazy_text_a_column:
  desc: null
  value: null
lazy_text_b_column:
  desc: null
  value: null
lazy_text_column:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 4.0e-05
local_rank:
  desc: null
  value: -1
logging_steps:
  desc: null
  value: 100
manual_seed:
  desc: null
  value: null
max_grad_norm:
  desc: null
  value: 1.0
max_seq_length:
  desc: null
  value: 128
model_class:
  desc: null
  value: ClassificationModel
model_name:
  desc: null
  value: bert-base-cased
model_type:
  desc: null
  value: bert
multiprocessing_chunksize:
  desc: null
  value: 500
n_gpu:
  desc: null
  value: 1
no_cache:
  desc: null
  value: false
no_save:
  desc: null
  value: false
num_train_epochs:
  desc: null
  value: 2
output_dir:
  desc: null
  value: outputs/
overwrite_output_dir:
  desc: null
  value: true
process_count:
  desc: null
  value: 6
regression:
  desc: null
  value: false
reprocess_input_data:
  desc: null
  value: true
save_best_model:
  desc: null
  value: true
save_eval_checkpoints:
  desc: null
  value: false
save_model_every_epoch:
  desc: null
  value: true
save_optimizer_and_scheduler:
  desc: null
  value: true
save_steps:
  desc: null
  value: 2000
silent:
  desc: null
  value: false
sliding_window:
  desc: null
  value: false
stride:
  desc: null
  value: 0.8
tensorboard_dir:
  desc: null
  value: null
thread_count:
  desc: null
  value: null
tie_value:
  desc: null
  value: 1
train_batch_size:
  desc: null
  value: 32
train_custom_parameters_only:
  desc: null
  value: false
use_cached_eval_features:
  desc: null
  value: false
use_early_stopping:
  desc: null
  value: false
use_multiprocessing:
  desc: null
  value: true
wandb_kwargs:
  desc: null
  value: {}
wandb_project:
  desc: null
  value: visualization-demo
warmup_ratio:
  desc: null
  value: 0.06
warmup_steps:
  desc: null
  value: 23
weight_decay:
  desc: null
  value: 0
