wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.6
    framework: torch
    huggingface_version: 3.1.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.1
